name: Update GitHub Avatar

on:
  schedule:
    - cron: "0 2 * * *"  # 每天凌晨 2 点自动运行
  workflow_dispatch:     # 允许你手动点一下运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt install -y imagemagick

      - name: Download avatar
        run: |
          # 替换成你的 GitHub 用户名
          GITHUB_USER="crazying-dev"
          
          # 下载头像
          curl -L "https://github.com/${GITHUB_USER}.png" -o raw-avatar.png

          # 生成 favicon.ico (16x16 32x32 48x48)
          convert raw-avatar.png -resize 48x48 \
            -define icon:auto-resize=48,32,16 assets/img/favicon.ico

          # 生成 me.png
          cp raw-avatar.png assets/img/me.png

          rm raw-avatar.png

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add assets/img/favicon.ico assets/img/me.png
          git commit -m "Auto update avatar [$(date)]" || exit 0
          git push